spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/person_service_data?currentSchema=public
    username: postgres
    password: 2009129x
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    data: classpath:init/data.sql
    schema: classpath:init/schema.sql
    initialization-mode: always



